apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: mar12-ragoldappnewimage-1
  janus-idp.io/tekton: mar12-ragoldappnewimage-1
  backstage.io/kubernetes-id: mar12-ragoldappnewimage-1
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: mar12-ragoldappnewimage-1
resources:
  - initialize-namespace.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
  - deployment-database.yaml
  - service-database.yaml
  - database-config.yaml
