apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mar12-ragoldappnewimage-1-gitops-repository
spec:
  url: https://github.com/jdubrick-ai/mar12-ragoldappnewimage-1-gitops
